name: Docker Build & Push

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Main Portfolio Docker image
      run: |
        docker build . --tag ghcr.io/upstride-edu/website:latest
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u PranavVerma-droid --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/upstride-edu/website:latest